############################################################
# Dockerfile
# Based on Python 2.7
# This is the Dev Build
############################################################
FROM python:2-onbuild

# File Author / Maintainer
MAINTAINER Robert Donovan <admin@mixfin.com>

# install our code
#add . /home/docker/code/

# run pip install

run pip install -r requirements.txt

run apt-get update